# Generated by Django 4.2.1 on 2023-11-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_app', '0002_burger_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='burger',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='burger_files/'),
        ),
    ]
